<?php

declare(strict_types=1);

use ArtisanBuild\Hallway\Channels\Enums\ChannelPermissionTypes;
use ArtisanBuild\Hallway\Channels\Enums\ChannelTestSwitches;
use ArtisanBuild\Hallway\Channels\Enums\ChannelTypes;
use ArtisanBuild\Hallway\Members\Enums\MemberRoles;
use ArtisanBuild\Hallway\Moderation\Enums\ModerationMemberStates;
use ArtisanBuild\Hallway\Payment\Enums\PaymentStates;

test('read permissions for private member channels', function (
    MemberRoles $role,
    PaymentStates $payment_state,
    ModerationMemberStates $moderation_state,
    ChannelTestSwitches $switch,
    bool $expected,
): void {
    channel_permissions(
        channel_type: ChannelTypes::MemberPrivate,
        permission_type: ChannelPermissionTypes::Read,
        role: $role,
        payment_state: $payment_state,
        moderation_state: $moderation_state,
        switch: $switch,
        expected: $expected,
    );
})->with([
    // Members and pseudo-members not subject to payment and moderation variation
    [MemberRoles::Owner, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Admin, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Moderator, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Guest, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    // Variation in Payment States
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    // Now test member types as exempt from payment on the moderation status variables
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::None, false],
]);

test('write permissions for private member channels', function (
    MemberRoles $role,
    PaymentStates $payment_state,
    ModerationMemberStates $moderation_state,
    ChannelTestSwitches $switch,
    bool $expected,
): void {
    channel_permissions(
        channel_type: ChannelTypes::MemberPrivate,
        permission_type: ChannelPermissionTypes::Write,
        role: $role,
        payment_state: $payment_state,
        moderation_state: $moderation_state,
        switch: $switch,
        expected: $expected,
    );
})->with([
    // Members and pseudo-members not subject to payment and moderation variation
    [MemberRoles::Owner, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Admin, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Moderator, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Guest, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Guest, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    // Variation in Payment States
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    // Now test member types as exempt from payment on the moderation status variables
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::None, false],
]);

test('comment permissions for private member channels', function (
    MemberRoles $role,
    PaymentStates $payment_state,
    ModerationMemberStates $moderation_state,
    ChannelTestSwitches $switch,
    bool $expected,
): void {
    channel_permissions(
        channel_type: ChannelTypes::MemberPrivate,
        permission_type: ChannelPermissionTypes::Comment,
        role: $role,
        payment_state: $payment_state,
        moderation_state: $moderation_state,
        switch: $switch,
        expected: $expected,
    );
})->with([
    // Members and pseudo-members not subject to payment and moderation variation
    [MemberRoles::Owner, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Admin, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Moderator, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Guest, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    // Variation in Payment States
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, true],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    // Now test member types as exempt from payment on the moderation status variables
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::None, false],
]);

test('invite permissions for private member channels', function (
    MemberRoles $role,
    PaymentStates $payment_state,
    ModerationMemberStates $moderation_state,
    ChannelTestSwitches $switch,
    bool $expected,
): void {
    channel_permissions(
        channel_type: ChannelTypes::MemberPrivate,
        permission_type: ChannelPermissionTypes::Invite,
        role: $role,
        payment_state: $payment_state,
        moderation_state: $moderation_state,
        switch: $switch,
        expected: $expected,
    );
})->with([
    // Members and pseudo-members not subject to payment and moderation variation
    [MemberRoles::Owner, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Admin, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Moderator, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadWriteBot, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Guest, PaymentStates::Exempt, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    // Variation in Payment States
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::OwnsChannel, true],
    [MemberRoles::Member, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::OwnsChannel, true],
    [MemberRoles::Member, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::OwnsChannel, true],
    [MemberRoles::Member, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::OwnsChannel, true],
    [MemberRoles::Member, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::OwnsChannel, true],
    [MemberRoles::Member, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::OwnsChannel, true],
    [MemberRoles::Member, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Premium, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::GracePeriod, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Trial, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Free, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Cancelled, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Suspended, ModerationMemberStates::Active, ChannelTestSwitches::None, false],
    // Now test member types as exempt from payment on the moderation status variables
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::None, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::Member, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Limited, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::LimitAppealed, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::Suspended, ChannelTestSwitches::None, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::InChannel, false],
    [MemberRoles::ReadOnlyMember, PaymentStates::Exempt, ModerationMemberStates::SuspensionAppealed, ChannelTestSwitches::None, false],
]);
